version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/enforce"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "17:00"
      timezone: "Asia/Calcutta"