version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/enforce"
    target-branch: "troubleshoot-cla-release-notes-updates"
    schedule:
      interval: "daily"
      time: "17:35"
      timezone: "Asia/Calcutta"