# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  sync:
    docker:
      - image: cimg/python:3.7
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install rsync
          command: |
            sudo apt update -y
            sudo apt install -y rsync
      - run:
          name: Install GH CLI
          command: |
            sudo apt install -y git
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0 
            sudo apt-add-repository -u https://cli.github.com/packages  -y
            sudo apt install gh -y
      - run:
          name: Install HUB CLI
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
            test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
            test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
            echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
            brew install hub
      - run:
          name: Install AWS CLI and kubectl
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: setup python
          command: pip install git+https://github.com/pixelb/crudini.git
      - run:
          name: Apply Configuration policy
          command: |
            test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
            test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
            echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
            ./sync.sh

workflows:
  sync:
    jobs:
      - approval-run:
          type: approval
      - sync:
          context:
            - gdi-reportportal
          requires:
            - approval-run
