##
## SPDX-FileCopyrightText: 2020 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-1-2020
##
##
name: SNYK Token Update

on:
  push:
    branches: [synk-token-troubleshoot]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Adding GitHub secrets into Addons
        run: |
          branch_name=$(echo ${GITHUB_REF##*/})
          SNYK_TOKEN_VALUE=${{secrets.SNYK_TOKEN}}
          while IFS=, read -r repo_name repo_id repo_access repo_description repo_branch
          do
              echo "Repo name: $repo_name"
              curl \
                -X PUT \
                -H "Accept: application/vnd.github.v3+json" \
                -H "authorization: token ${{ secrets.GITHUB_TOKEN }}"\
                https://api.github.com/repos/splunk/addonfactory-repository-template/actions/secrets/TEST_TOKEN \
                -d '{"encrypted_value": "hello_world" }'
          done < repositories_$branch_name.csv