##
## SPDX-FileCopyrightText: 2020 Splunk, Inc. <sales@splunk.com>
## SPDX-License-Identifier: LicenseRef-Splunk-1-2020
##
##
name: SNYK Token Update

on:
  push:
    branches: [synk-token-troubleshoot]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Adding GitHub secrets into Addons
        run: |
          branch_name=$(echo ${GITHUB_REF##*/})
          SYNK_TOKEN_WITH_SPACES=\"$(echo ${{secrets.SNYK_TOKEN}} | sed 's/./& /g')\"
          echo $SYNK_TOKEN_WITH_SPACES > abc.txt
          echo $SYNK_TOKEN_WITH_SPACES
          SNYK_TOKEN_VALUE=$(cat abc.txt | sed 's/ //g')
          echo "$SNYK_TOKEN_VALUE"
          # while IFS=, read -r repo_name repo_id repo_access repo_description repo_branch
          # do
          #     echo "Repo name: $repo_name"
          #     curl \
          #       -X PUT \
          #       -H "Accept: application/vnd.github.v3+json" \
          #       -H "authorization: token ${{ secrets.GH_TOKEN_ADMIN }}"\
          #       https://api.github.com/repos/splunk/$repo_name/actions/secrets/SNYK_TOKEN \
          #       -d '{"encrypted_value": "$SNYK_TOKEN_VALUE" }'
          # done < repositories_$branch_name.csv